// Auto-generated by tools/extractBoardData.mjs — do not edit manually.

export type BoardDefinition = {
  nickname: string;
  imageUrl: string;
};

export const BOARDS: BoardDefinition[] = [
  { nickname: "A", imageUrl: "/boards/Board A.png" },
  { nickname: "B", imageUrl: "/boards/Board B.png" },
  { nickname: "C", imageUrl: "/boards/Board C.png" },
  { nickname: "D", imageUrl: "/boards/Board D.png" },
  { nickname: "E", imageUrl: "/boards/Board E.png" },
  { nickname: "F", imageUrl: "/boards/Board F.png" },
  { nickname: "G", imageUrl: "/boards/Board G.png" },
  { nickname: "H", imageUrl: "/boards/Board H.png" },
];

export const BOARD_NICKNAMES = BOARDS.map(b => b.nickname);

export function getBoardByNickname(nickname: string): BoardDefinition | undefined {
  return BOARDS.find(b => b.nickname === nickname);
}
