import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(process.cwd());

const inputPath = path.join(root, 'Assets', 'decks', 'Balanced Boards.json');
const outputPath = path.join(root, 'frontend', 'src', 'data', 'boards.ts');

const raw = JSON.parse(fs.readFileSync(inputPath, 'utf-8'));
const contained = raw.ObjectStates[0].ContainedObjects;

const boards = contained
  .filter(obj => obj.Nickname && obj.CustomImage?.ImageURL)
  .map(obj => ({
    nickname: obj.Nickname,
    imageUrl: obj.CustomImage.ImageURL,
  }))
  .sort((a, b) => a.nickname.localeCompare(b.nickname));

const ts = `// Auto-generated by tools/extractBoardData.mjs — do not edit manually.

export type BoardDefinition = {
  nickname: string;
  imageUrl: string;
};

export const BOARDS: BoardDefinition[] = ${JSON.stringify(boards, null, 2)};

export const BOARD_NICKNAMES = BOARDS.map(b => b.nickname);

export function getBoardByNickname(nickname: string): BoardDefinition | undefined {
  return BOARDS.find(b => b.nickname === nickname);
}
`;

fs.writeFileSync(outputPath, ts, 'utf-8');
console.log(`[OK] Wrote ${boards.length} boards to ${outputPath}`);
boards.forEach(b => console.log(`  ${b.nickname}: ${b.imageUrl}`));
